import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientToaster from "@/components/shared/ClientToaster";
import Navbar from "@/components/navigation/Navbar";
import { Footer } from "@/components/footer/Footer";
import { BottomMobileNavWrapper } from "@/components/navigation/_wrappers/BottomMobileNavWrapper";
import VerifyEmailModal from "@/components/shared/VerifyEmailModal";
import CookieConsentProvider from "@/components/cookies-consent/CookieConsentProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1">{children}</main>
          <BottomMobileNavWrapper />
          <Footer />
          <CookieConsentProvider />
          <ClientToaster />
          <VerifyEmailModal />
        </div>
      </body>
    </html>
  );
}
